from __future__ import annotations

from pathlib import Path
from typing import Protocol


class StorageEngine(Protocol):
    """Abstract interface for binary I/O operations."""

    # Upload lifecycle
    def initialize_upload(self, upload_id: str) -> None: ...
    def write_chunk(self, upload_id: str, index: int, data: bytes) -> None: ...
    def get_chunk_size(self, upload_id: str, index: int) -> int | None: ...
    def list_uploaded_chunks(self, upload_id: str) -> list[int]: ...
    def abort_upload(self, upload_id: str) -> None: ...

    # CAS operations
    def commit_upload_to_cas(
        self,
        upload_id: str,
        expected_sha256: str | None,
        expected_size: int | None,
    ) -> tuple[str, int]: ...

    def commit_file_to_cas(self, src_path: Path) -> tuple[str, int]: ...

    # Path resolution
    def get_cas_blob_path(self, blob_hash: str) -> Path: ...
    def get_job_workspace_dir(self, job_id: str) -> Path: ...

    # Study filesystem management (raw/ vs derived/ under studies/{study_id}/)
    def link_original_file_to_study(
        self, study_id: str, filename: str, blob_hash: str
    ) -> Path: ...

    def link_derived_file_to_study(
        self, study_id: str, filename: str, blob_hash: str
    ) -> Path: ...

    def remove_study_data(self, study_id: str) -> None: ...

    # GC
    def delete_blob(self, blob_hash: str) -> None: ...
    def sweep_orphaned_blobs(self) -> int: ...
